name: Build Image

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Dowload the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: pip install -r requirements.txt ruff pytest httpx
      
      - name: Lint
        run: ruff check .

      - name: Test
        run: pytest

  build:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Dowload the repository
        uses: actions/checkout@v4

      - name: Build the docker image
        run: docker build -t dental-ben:test .


